import type { AdventureZoneDef } from './types';

export const MATH_ADVENTURE_ZONES: AdventureZoneDef[] = [
  {
    id: 'zone-maketen',
    name: 'はじまりの もり',
    emoji: '🌳',
    bgFrom: 'from-green-100',
    bgTo: 'to-emerald-200',
    unitIds: ['make-ten'],
    layerCount: 8,
    tagline: '10を つくって もりを すすもう',
    story: 'まほうの もりに やってきた！\nかずを あわせて 10に すると、\nとびらが ひらくよ。',
    wall: '🌿',
    tint: 'rgba(80,160,80,.22)',
  },
  {
    id: 'zone-addition',
    name: 'たしざんの みち',
    emoji: '➕',
    bgFrom: 'from-sky-100',
    bgTo: 'to-blue-200',
    unitIds: ['addition'],
    layerCount: 8,
    tagline: 'かずを たして みちを ひらこう',
    story: 'まほうの かずのいしが みちに ならんでいる。\nたしざんを とくと、いしが ひかって\n つぎの みちが あらわれるよ！',
    wall: '✨',
    tint: 'rgba(70,130,200,.22)',
  },
  {
    id: 'zone-subtraction',
    name: 'ひきざんの はら',
    emoji: '➖',
    bgFrom: 'from-orange-100',
    bgTo: 'to-amber-200',
    unitIds: ['subtraction'],
    layerCount: 8,
    tagline: 'ひいて ひいて はらを こえよう',
    story: 'ひろい はらっぱに いっぱいの かず。\nひきざんで かずを へらすと、\nはらの むこうに みちが みえてくるよ！',
    wall: '🌾',
    tint: 'rgba(200,120,50,.22)',
  },
  {
    id: 'zone-cherry',
    name: 'さくらんぼの おか',
    emoji: '🍒',
    bgFrom: 'from-rose-100',
    bgTo: 'to-pink-200',
    unitIds: ['cherry-calc'],
    layerCount: 8,
    tagline: 'さくらんぼに わけて おかを こえよう',
    story: 'おかには さくらんぼの きが いっぱい。\nかずを さくらんぼに わけると、\n くりあがりも かんたんに なるよ！',
    wall: '🍒',
    tint: 'rgba(200,80,100,.22)',
  },
  {
    // 前半（10づくり・たし・ひき・さくらんぼ）を まぜて おさらい
    // ＝間隔をあけた くりかえし＋いろんな しゅるいを 交互に（spacing / interleaving）
    id: 'zone-review-basics',
    name: 'おさらいの ひろば',
    emoji: '🧮',
    bgFrom: 'from-emerald-100',
    bgTo: 'to-teal-200',
    unitIds: ['make-ten', 'addition', 'subtraction', 'cherry-calc'],
    layerCount: 8,
    tagline: 'いままでの たしひきを まぜて おさらい',
    story: 'ひろばで いままでの ちからを ためそう。\n10づくりも たしざんも ひきざんも、\nまぜて とくと もっと つよくなるよ！',
    wall: '🍀',
    tint: 'rgba(60,170,140,.22)',
  },
  {
    id: 'zone-bigadd',
    name: 'ふたけたの まち',
    emoji: '🏘️',
    bgFrom: 'from-violet-100',
    bgTo: 'to-purple-200',
    unitIds: ['big-addition'],
    layerCount: 8,
    tagline: '2けたのたしざんで まちを ひらこう',
    story: 'おおきな まちに やってきた。\n10のくらいと 1のくらいを わけると、\n2けたも こわくないよ！',
    wall: '🏠',
    tint: 'rgba(130,80,200,.22)',
  },
  {
    id: 'zone-word',
    name: 'ぴったり みなと',
    emoji: '⚓',
    bgFrom: 'from-teal-100',
    bgTo: 'to-cyan-200',
    unitIds: ['word-addition', 'word-subtraction'],
    layerCount: 8,
    tagline: 'ぴったりの こたえを みつけて みなとへ',
    story: 'みなとには ふねが まっている。\nもんだいぶんを よんで、\nたすのか ひくのかを みきわめよう！',
    wall: '⛵',
    tint: 'rgba(50,160,160,.22)',
  },
  {
    id: 'zone-rotation',
    name: 'くるくる アトリエ',
    emoji: '🔄',
    bgFrom: 'from-yellow-100',
    bgTo: 'to-lime-200',
    unitIds: ['shape-rotation'],
    layerCount: 8,
    tagline: 'かたちを まわして アトリエを たんけん',
    story: 'ふしぎな アトリエに やってきた。\nかたちを くるくる まわすと、\nなにか あたらしい すがたに なるよ！',
    wall: '🎨',
    tint: 'rgba(180,180,50,.22)',
  },
  {
    id: 'zone-compose',
    name: 'かたちあわせ こうぼう',
    emoji: '🧩',
    bgFrom: 'from-indigo-100',
    bgTo: 'to-blue-200',
    unitIds: ['shape-compose'],
    layerCount: 8,
    tagline: 'かたちを くみあわせて こうぼうを ひらこう',
    story: 'こうぼうには いろんな かたちの ピース。\nうまく くみあわせると、\nおおきな かたちが できるよ！',
    wall: '🔶',
    tint: 'rgba(80,80,200,.22)',
  },
  {
    id: 'zone-pattern',
    name: 'もようの にわ',
    emoji: '🔁',
    bgFrom: 'from-fuchsia-100',
    bgTo: 'to-pink-200',
    unitIds: ['shape-pattern', 'shape-spatial'],
    layerCount: 8,
    tagline: 'もようの ひみつを みつけて にわを すすもう',
    story: 'にわには ふしぎな もようが いっぱい。\nパターンを みつけて、\nつぎに くる かたちを あてよう！',
    wall: '🌸',
    tint: 'rgba(180,80,180,.22)',
  },
  {
    id: 'zone-bigsub',
    name: 'ふたけたの ひきざん',
    emoji: '🏚️',
    bgFrom: 'from-stone-100',
    bgTo: 'to-orange-200',
    unitIds: ['big-subtraction'],
    layerCount: 8,
    tagline: 'ふたけたから ひとけたを ひこう',
    story: 'ふたけたの まちの うらどおり。\nおおきい かずから ひとけたを ひくよ。\nくりさがりに きを つけて！',
    wall: '🧱',
    tint: 'rgba(150,110,70,.22)',
  },
  {
    id: 'zone-mul',
    name: 'かけざんの もり',
    emoji: '✖️',
    bgFrom: 'from-lime-100',
    bgTo: 'to-green-200',
    unitIds: ['multiplication'],
    layerCount: 8,
    tagline: 'かたまりで まとめて かぞえよう',
    story: 'おなじ かずの かたまりが\nいくつも ならぶ もり。\nかけざんで まとめて かぞえよう！',
    wall: '🌳',
    tint: 'rgba(80,160,90,.22)',
  },
  {
    id: 'zone-div',
    name: 'わけわけ どうくつ',
    emoji: '➗',
    bgFrom: 'from-slate-100',
    bgTo: 'to-gray-300',
    unitIds: ['division'],
    layerCount: 8,
    tagline: 'おなじ かずずつ わけよう',
    story: 'くらい どうくつで みつけた おかし。\nみんなで おなじ かずずつ\nわけて みよう！',
    wall: '🪨',
    tint: 'rgba(110,110,120,.22)',
  },
  {
    id: 'zone-divrem',
    name: 'あまりんぼの たに',
    emoji: '🧩',
    bgFrom: 'from-pink-100',
    bgTo: 'to-rose-200',
    unitIds: ['division-remainder'],
    layerCount: 8,
    tagline: 'わりきれない かずに ちょうせん',
    story: 'わけても わけても のこっちゃう。\nこれが「あまり」だよ。\nなんこ あまるか かんがえよう！',
    wall: '🍰',
    tint: 'rgba(200,90,130,.22)',
  },
  {
    id: 'zone-mix',
    name: 'ちからだめし ひろば',
    emoji: '🌈',
    bgFrom: 'from-amber-100',
    bgTo: 'to-pink-200',
    unitIds: ['cherry-calc', 'big-addition', 'big-subtraction', 'multiplication', 'division'],
    layerCount: 8,
    tagline: 'いままでの ちからで ぜんぶ とこう',
    story: 'いままで おぼえた ぜんぶの ちから。\nたしざんも かけざんも わりざんも、\nここで ためして みよう！',
    wall: '⭐',
    tint: 'rgba(200,140,80,.22)',
  },
  {
    id: 'zone-boss',
    name: 'だいとしょかんの おく',
    emoji: '🌟',
    bgFrom: 'from-amber-100',
    bgTo: 'to-yellow-200',
    unitIds: ['make-ten', 'addition', 'subtraction', 'cherry-calc', 'big-addition'],
    layerCount: 10,
    tagline: 'ぜんぶの ちしきで ラスボスに ちょうせん！',
    story: 'いよいよ としょかんの おくへ。\nこれまで おぼえた ぜんぶを つかって、\nさいごの ひみつを といてみよう！',
    wall: '📚',
    tint: 'rgba(200,150,50,.22)',
  },
  // ── 理数センス道場（ラスボス後に解放される 上級の まき） ──
  {
    id: 'zone-numberline',
    name: 'かずの しまわたり',
    emoji: '🐸',
    bgFrom: 'from-sky-100',
    bgTo: 'to-cyan-200',
    unitIds: ['number-line'],
    layerCount: 8,
    tagline: 'カエルが いる かずを あてよう',
    story: 'かわに かずの しまが いっぱい。\nカエルが どの かずに いるか、\nめもりを みて あててね！',
    wall: '🪷',
    tint: 'rgba(70,150,210,.22)',
  },
  {
    id: 'zone-estimate',
    name: 'かぞえる もり',
    emoji: '🍪',
    bgFrom: 'from-amber-100',
    bgTo: 'to-orange-200',
    unitIds: ['estimate-pile'],
    layerCount: 8,
    tagline: '10ずつ かぞえて なんこ?',
    story: 'もりには おやつが どっさり。\n10ずつの かたまりで かぞえると、\nなんこ あるか すぐ わかるよ！',
    wall: '🌰',
    tint: 'rgba(210,150,70,.22)',
  },
  {
    id: 'zone-tenframe',
    name: 'パッとそろばん',
    emoji: '⚡',
    bgFrom: 'from-violet-100',
    bgTo: 'to-fuchsia-200',
    unitIds: ['ten-frame-sum'],
    layerCount: 8,
    tagline: '10の枠で パッと たしざん',
    story: '10の まほうの枠が ならぶ へや。\n「5と3で8」みたいに、かたまりで\nパッと よむと、はやく こたえられるよ！',
    wall: '🔢',
    tint: 'rgba(150,90,210,.22)',
  },
  {
    id: 'zone-tenframe-sub',
    name: 'パッとひきざん',
    emoji: '✂️',
    bgFrom: 'from-rose-100',
    bgTo: 'to-red-200',
    unitIds: ['ten-frame-sub'],
    layerCount: 8,
    tagline: '10の枠で パッと ひきざん',
    story: '10の まほうの枠から おやつを とるよ。\nとった ぶんは ✕に なるから、\nのこりが いくつか パッと よんでね！',
    wall: '✂️',
    tint: 'rgba(210,90,90,.22)',
  },
  {
    id: 'zone-tenframe-ten',
    name: '10の おともだち',
    emoji: '🤝',
    bgFrom: 'from-teal-100',
    bgTo: 'to-emerald-200',
    unitIds: ['ten-frame-complement'],
    layerCount: 8,
    tagline: 'あと いくつで 10？',
    story: '10に なると なかよしの しるし。\nいま いくつ あるか パッと みて、\nあと いくつで 10に なるか こたえてね！',
    wall: '🟢',
    tint: 'rgba(70,180,140,.22)',
  },
  // ── スーパーマーケットの くに（タングラムで かたちを かんがえる 3つの まき）──
  {
    id: 'zone-tangram-compose',
    name: 'いりぐちの ひろば',
    emoji: '🛒',
    bgFrom: 'from-rose-100',
    bgTo: 'to-orange-200',
    unitIds: ['tangram-compose'],
    layerCount: 8,
    tagline: 'ピースを あわせて しなものを つくろう',
    story: 'スーパーマーケットの くにへ ようこそ！\nさんかくや しかくの ピースを あわせると、\nおみせの しなものに へんしんするよ。',
    wall: '🛒',
    tint: 'rgba(240,140,90,.22)',
  },
  {
    id: 'zone-tangram-missing',
    name: 'パンの コーナー',
    emoji: '🥐',
    bgFrom: 'from-amber-100',
    bgTo: 'to-yellow-200',
    unitIds: ['tangram-missing'],
    layerCount: 8,
    tagline: 'たりない ピースを みつけよう',
    story: 'やきたての パンの コーナー。\nかたちが すこし かけちゃった！\nぴったり あう ピースを えらんでね。',
    wall: '🥐',
    tint: 'rgba(230,170,70,.22)',
  },
  {
    id: 'zone-tangram-decompose',
    name: 'チーズの たな',
    emoji: '🧀',
    bgFrom: 'from-yellow-100',
    bgTo: 'to-lime-200',
    unitIds: ['tangram-decompose'],
    layerCount: 8,
    tagline: 'どの ピースで できてるか みやぶろう',
    story: 'いろんな しなものが ならぶ たな。\nこの かたちは どの ピースを\nあわせて できているのかな？',
    wall: '🧀',
    tint: 'rgba(220,200,60,.22)',
  },
  // ── パッと出す くに（一瞬で 見て こたえる 3つの まき）──
  {
    id: 'zone-teen-frame',
    name: '20までの へや',
    emoji: '🔢',
    bgFrom: 'from-sky-100',
    bgTo: 'to-indigo-200',
    unitIds: ['ten-frame-teen'],
    layerCount: 8,
    tagline: '10と いくつで パッと いくつ？',
    story: '10の まほうの枠が いっぱいの へや。\n10の かたまりと のこりを 見て、\n「10と いくつ」で パッと よもう！',
    wall: '🔢',
    tint: 'rgba(90,110,210,.22)',
  },
  {
    id: 'zone-coins',
    name: 'おかいもの レジ',
    emoji: '💰',
    bgFrom: 'from-amber-100',
    bgTo: 'to-yellow-200',
    unitIds: ['coins'],
    layerCount: 8,
    tagline: 'こうかを かぞえて なんえん？',
    story: 'レジに おかねが ならんでいる。\n100が なんまい、10が なんまい…\nかたまりで かぞえて ごうけいを だそう！',
    wall: '🪙',
    tint: 'rgba(210,170,60,.22)',
  },
  {
    id: 'zone-mul-flash',
    name: 'パッと かけ算',
    emoji: '✖️',
    bgFrom: 'from-lime-100',
    bgTo: 'to-emerald-200',
    unitIds: ['mul-flash'],
    layerCount: 8,
    tagline: '×2・×5を パッと こたえよう',
    story: 'おなじ かずの かたまりが ならぶ。\n2つぶん・5つぶんを パッと、\nかけ算で まとめて かぞえよう！',
    wall: '✖️',
    tint: 'rgba(90,180,110,.22)',
  },
  // ── かたちの くに（目で 見て くらべる・うつす 3つの まき）──
  {
    id: 'zone-mirror',
    name: 'かがみの へや',
    emoji: '🪞',
    bgFrom: 'from-cyan-100',
    bgTo: 'to-sky-200',
    unitIds: ['shape-mirror'],
    layerCount: 8,
    tagline: 'かがみに うつすと どんな かたち？',
    story: 'ふしぎな かがみの へや。\nかがみに うつすと 左右が ひっくりかえる。\nまわすのと どう ちがうか みくらべよう！',
    wall: '🪞',
    tint: 'rgba(80,180,210,.22)',
  },
  {
    id: 'zone-tangram-advanced',
    name: 'おかしの コーナー',
    emoji: '🍰',
    bgFrom: 'from-rose-100',
    bgTo: 'to-pink-200',
    unitIds: ['tangram-advanced'],
    layerCount: 8,
    tagline: 'たくさんの ピースで かたちを つくろう',
    story: 'あまーい おかしの コーナー。\n3つや 4つの ピースを あわせると、\nだいけいや ダイヤも つくれるよ！',
    wall: '🍰',
    tint: 'rgba(220,110,150,.22)',
  },
  {
    id: 'zone-size-compare',
    name: 'おおきさくらべ',
    emoji: '📏',
    bgFrom: 'from-teal-100',
    bgTo: 'to-green-200',
    unitIds: ['size-compare'],
    layerCount: 8,
    tagline: 'いちばん おおきい／ながいのは どれ？',
    story: 'おおきさも ながさも バラバラ。\nよーく 見くらべて、いちばんを\nさがしだそう！',
    wall: '📏',
    tint: 'rgba(70,180,150,.22)',
  },
  // ── まとめて かぞえる くに（かけ算の はじめ・かたまりを わくで 見せる 3つの まき）──
  {
    id: 'zone-mul-look',
    name: 'はこの なかみ',
    emoji: '📦',
    bgFrom: 'from-lime-100',
    bgTo: 'to-emerald-200',
    unitIds: ['mul-look-total'],
    layerCount: 8,
    tagline: 'かたまりを 見て ぜんぶで なんこ？',
    story: 'おなじ かずの かたまりが\nわくの なかに ならんでいる。\nぜんぶで なんこか かぞえてみよう！',
    wall: '📦',
    tint: 'rgba(90,180,110,.22)',
  },
  {
    id: 'zone-mul-count',
    name: 'いくつの かたまり',
    emoji: '🔢',
    bgFrom: 'from-emerald-100',
    bgTo: 'to-teal-200',
    unitIds: ['mul-count-groups'],
    layerCount: 8,
    tagline: 'かたまりは いくつ ある？',
    story: 'おなじ かずずつ かたまりに なってる。\nかたまりが いくつ あるか、\nわくを かぞえて あててね！',
    wall: '🟩',
    tint: 'rgba(60,170,140,.22)',
  },
  {
    id: 'zone-mul-flash-total',
    name: 'パッと まとめて',
    emoji: '⚡',
    bgFrom: 'from-yellow-100',
    bgTo: 'to-lime-200',
    unitIds: ['mul-flash-total'],
    layerCount: 8,
    tagline: '一瞬だけ 見て ぜんぶで なんこ？',
    story: 'かたまりが パッと あらわれて かくれる！\nよく 見て おぼえて、\nぜんぶで なんこか あててね！',
    wall: '✨',
    tint: 'rgba(200,180,60,.22)',
  },
  // ── わけて かぞえる くに（わり算の はじめ・おさら／人で くばる 3つの まき）──
  {
    id: 'zone-div-look',
    name: 'おさらに わけて',
    emoji: '🍽️',
    bgFrom: 'from-sky-100',
    bgTo: 'to-cyan-200',
    unitIds: ['div-look-total'],
    layerCount: 8,
    tagline: 'おさらに くばって ぜんぶで なんこ？',
    story: 'おさらに おなじ かずずつ\nくばって あるよ。\nぜんぶで なんこか かぞえてみよう！',
    wall: '🍽️',
    tint: 'rgba(70,160,200,.22)',
  },
  {
    id: 'zone-div-people',
    name: 'なん人で わけた？',
    emoji: '🙂',
    bgFrom: 'from-indigo-100',
    bgTo: 'to-blue-200',
    unitIds: ['div-count-people'],
    layerCount: 8,
    tagline: 'なん人で わけたか あててね',
    story: 'おなじ かずずつ みんなに くばったよ。\nなん人で わけたのか、\nくばった ぶんを かぞえて あててね！',
    wall: '🙂',
    tint: 'rgba(90,110,200,.22)',
  },
  {
    id: 'zone-div-flash',
    name: 'パッと わけわけ',
    emoji: '⚡',
    bgFrom: 'from-fuchsia-100',
    bgTo: 'to-pink-200',
    unitIds: ['div-flash-total'],
    layerCount: 8,
    tagline: '一瞬だけ 見て ぜんぶで なんこ？',
    story: 'くばった ようすが パッと きえる！\nよく 見て おぼえて、\nぜんぶで なんこか あててね！',
    wall: '💫',
    tint: 'rgba(190,80,180,.22)',
  },
  // ── もっと かけ算（同数累加・アレイ・○ばい で かけ算の 見かたを ひろげる）──
  {
    id: 'zone-mul-repeated',
    name: 'たして かぞえる はらっぱ',
    emoji: '🌻',
    bgFrom: 'from-lime-100',
    bgTo: 'to-yellow-200',
    unitIds: ['mul-repeated'],
    layerCount: 8,
    tagline: 'おなじ かずを たして まとめよう',
    story: 'はらっぱに おなじ かずの かたまりが いっぱい。\n2＋2＋2…と たしていくと、\nかけ算の はじまりに なるよ！',
    wall: '🌼',
    tint: 'rgba(150,180,60,.22)',
  },
  {
    id: 'zone-mul-array',
    name: 'ならんだ タイルの へや',
    emoji: '🟦',
    bgFrom: 'from-sky-100',
    bgTo: 'to-indigo-200',
    unitIds: ['mul-array'],
    layerCount: 8,
    tagline: 'たて と よこで まとめて かぞえよう',
    story: 'ゆかに タイルが きれいに ならぶ へや。\nたてと よこの かずが わかれば、\nぜんぶの かずも すぐ わかるよ！',
    wall: '🔷',
    tint: 'rgba(90,120,210,.22)',
  },
  {
    id: 'zone-mul-double',
    name: '○ばいの まほうじん',
    emoji: '✨',
    bgFrom: 'from-fuchsia-100',
    bgTo: 'to-purple-200',
    unitIds: ['mul-double'],
    layerCount: 8,
    tagline: '○ばいに ふやすと いくつ？',
    story: 'まほうじんに のせると かずが ふえる！\n2ばい・3ばい…と かぞえると、\nこれも かけ算に なっているよ。',
    wall: '🔮',
    tint: 'rgba(170,90,200,.22)',
  },
  // ── もっと わり算（いくつ分＝包含除／1つ分＝等分除）──
  {
    id: 'zone-div-pack',
    name: 'ふくろづめ こうじょう',
    emoji: '🛍️',
    bgFrom: 'from-teal-100',
    bgTo: 'to-emerald-200',
    unitIds: ['div-pack'],
    layerCount: 8,
    tagline: '○こずつ つめると なんふくろ？',
    story: 'こうじょうで おかしを ふくろに つめるよ。\nおなじ かずずつ 入れていくと、\nふくろは なんこ できるかな？',
    wall: '🎁',
    tint: 'rgba(60,170,150,.22)',
  },
  {
    id: 'zone-div-fair',
    name: 'わけっこ ひろば',
    emoji: '🤝',
    bgFrom: 'from-rose-100',
    bgTo: 'to-orange-200',
    unitIds: ['div-fair'],
    layerCount: 8,
    tagline: 'みんなで おなじ かずずつ わけよう',
    story: 'ひろばで みんなに おやつを くばるよ。\nおなじ かずずつ わけると、\nひとり なんこ もらえるかな？',
    wall: '🍬',
    tint: 'rgba(230,130,110,.23)',
  },
  // ── かんたんめな 2けたの たしざん（やさしい→くりあがり へ 3だんかい）──
  {
    id: 'zone-big-add-1',
    name: 'はじめての 2けた',
    emoji: '🔢',
    bgFrom: 'from-sky-100',
    bgTo: 'to-cyan-200',
    unitIds: ['big-add-1'],
    layerCount: 8,
    tagline: '2けた＋1けた から はじめよう',
    story: 'おおきな かずの まちに やってきた。\nまずは 2けたに 1けたを たすよ。\nいちの くらいだけ たせば いいんだ！',
    wall: '🏠',
    tint: 'rgba(70,150,200,.22)',
  },
  {
    id: 'zone-big-add-nc',
    name: 'くらいごとの みち',
    emoji: '🧮',
    bgFrom: 'from-violet-100',
    bgTo: 'to-blue-200',
    unitIds: ['big-add-nc'],
    layerCount: 8,
    tagline: '2けた＋2けた を くらいで わけて',
    story: 'みちが 10のくらいと 1のくらいに わかれてる。\nそれぞれの くらいで たすと、\n2けた＋2けたも かんたんだよ！',
    wall: '🛤️',
    tint: 'rgba(120,100,200,.22)',
  },
  {
    id: 'zone-big-add-carry',
    name: 'くりあがりの まち',
    emoji: '⤴️',
    bgFrom: 'from-amber-100',
    bgTo: 'to-orange-200',
    unitIds: ['big-add-carry'],
    layerCount: 8,
    tagline: 'いちの くらいが 10を こえたら？',
    story: 'いちの くらいが 10を こえる まち。\nこえた ぶんは じゅうの くらいへ おひっこし！\nくりあがりに きを つけて たそう。',
    wall: '🏙️',
    tint: 'rgba(220,150,70,.22)',
  },
  // ── かたちの くに（既存メカを まぜた おさらい／タングラム そうごう）──
  {
    id: 'zone-shape-atelier',
    name: 'ひみつの アトリエ',
    emoji: '🎨',
    bgFrom: 'from-pink-100',
    bgTo: 'to-rose-200',
    unitIds: ['shape-rotation', 'shape-compose', 'shape-pattern', 'shape-spatial'],
    layerCount: 8,
    tagline: 'まわす・あわせる・もよう を まぜて',
    story: 'いろんな かたちが あつまる アトリエ。\nまわしたり あわせたり もようを よんだり、\nかたちの ちからを ぜんぶ ためそう！',
    wall: '🖼️',
    tint: 'rgba(220,110,150,.22)',
  },
  {
    id: 'zone-tangram-dojo',
    name: 'タングラム どうじょう',
    emoji: '🧩',
    bgFrom: 'from-yellow-100',
    bgTo: 'to-lime-200',
    unitIds: ['tangram-compose', 'tangram-missing', 'tangram-decompose', 'tangram-advanced'],
    layerCount: 8,
    tagline: 'ピースの わざを ぜんぶ つかおう',
    story: 'タングラムの たつじんが まつ どうじょう。\nくみあわせ・たりないピース・ぶんかい…\nならった わざで かたちを みやぶれ！',
    wall: '🔶',
    tint: 'rgba(200,190,60,.22)',
  },
];

export function getZone(id: string): AdventureZoneDef {
  const z = MATH_ADVENTURE_ZONES.find((z) => z.id === id);
  if (!z) throw new Error(`zone not found: ${id}`);
  return z;
}
