import type { AdventureZoneDef } from './types';

export const MATH_ADVENTURE_ZONES: AdventureZoneDef[] = [
  {
    id: 'zone-maketen',
    name: 'はじまりの もり',
    emoji: '🌳',
    bgFrom: 'from-green-100',
    bgTo: 'to-emerald-200',
    unitIds: ['make-ten'],
    layerCount: 8,
    tagline: '10を つくって もりを すすもう',
    story: 'まほうの もりに やってきた！\nかずを あわせて 10に すると、\nとびらが ひらくよ。',
    wall: '🌿',
    tint: 'rgba(80,160,80,.22)',
  },
  {
    id: 'zone-addition',
    name: 'たしざんの みち',
    emoji: '➕',
    bgFrom: 'from-sky-100',
    bgTo: 'to-blue-200',
    unitIds: ['addition'],
    layerCount: 8,
    tagline: 'かずを たして みちを ひらこう',
    story: 'まほうの かずのいしが みちに ならんでいる。\nたしざんを とくと、いしが ひかって\n つぎの みちが あらわれるよ！',
    wall: '✨',
    tint: 'rgba(70,130,200,.22)',
  },
  {
    id: 'zone-subtraction',
    name: 'ひきざんの はら',
    emoji: '➖',
    bgFrom: 'from-orange-100',
    bgTo: 'to-amber-200',
    unitIds: ['subtraction'],
    layerCount: 8,
    tagline: 'ひいて ひいて はらを こえよう',
    story: 'ひろい はらっぱに いっぱいの かず。\nひきざんで かずを へらすと、\nはらの むこうに みちが みえてくるよ！',
    wall: '🌾',
    tint: 'rgba(200,120,50,.22)',
  },
  {
    id: 'zone-cherry',
    name: 'さくらんぼの おか',
    emoji: '🍒',
    bgFrom: 'from-rose-100',
    bgTo: 'to-pink-200',
    unitIds: ['cherry-calc'],
    layerCount: 8,
    tagline: 'さくらんぼに わけて おかを こえよう',
    story: 'おかには さくらんぼの きが いっぱい。\nかずを さくらんぼに わけると、\n くりあがりも かんたんに なるよ！',
    wall: '🍒',
    tint: 'rgba(200,80,100,.22)',
  },
  {
    id: 'zone-bigadd',
    name: 'ふたけたの まち',
    emoji: '🏘️',
    bgFrom: 'from-violet-100',
    bgTo: 'to-purple-200',
    unitIds: ['big-addition'],
    layerCount: 8,
    tagline: '2けたのたしざんで まちを ひらこう',
    story: 'おおきな まちに やってきた。\n10のくらいと 1のくらいを わけると、\n2けたも こわくないよ！',
    wall: '🏠',
    tint: 'rgba(130,80,200,.22)',
  },
  {
    id: 'zone-word',
    name: 'ぴったり みなと',
    emoji: '⚓',
    bgFrom: 'from-teal-100',
    bgTo: 'to-cyan-200',
    unitIds: ['word-addition', 'word-subtraction'],
    layerCount: 8,
    tagline: 'ぴったりの こたえを みつけて みなとへ',
    story: 'みなとには ふねが まっている。\nもんだいぶんを よんで、\nたすのか ひくのかを みきわめよう！',
    wall: '⛵',
    tint: 'rgba(50,160,160,.22)',
  },
  {
    id: 'zone-rotation',
    name: 'くるくる アトリエ',
    emoji: '🔄',
    bgFrom: 'from-yellow-100',
    bgTo: 'to-lime-200',
    unitIds: ['shape-rotation'],
    layerCount: 8,
    tagline: 'かたちを まわして アトリエを たんけん',
    story: 'ふしぎな アトリエに やってきた。\nかたちを くるくる まわすと、\nなにか あたらしい すがたに なるよ！',
    wall: '🎨',
    tint: 'rgba(180,180,50,.22)',
  },
  {
    id: 'zone-compose',
    name: 'かたちあわせ こうぼう',
    emoji: '🧩',
    bgFrom: 'from-indigo-100',
    bgTo: 'to-blue-200',
    unitIds: ['shape-compose'],
    layerCount: 8,
    tagline: 'かたちを くみあわせて こうぼうを ひらこう',
    story: 'こうぼうには いろんな かたちの ピース。\nうまく くみあわせると、\nおおきな かたちが できるよ！',
    wall: '🔶',
    tint: 'rgba(80,80,200,.22)',
  },
  {
    id: 'zone-pattern',
    name: 'もようの にわ',
    emoji: '🔁',
    bgFrom: 'from-fuchsia-100',
    bgTo: 'to-pink-200',
    unitIds: ['shape-pattern', 'shape-spatial'],
    layerCount: 8,
    tagline: 'もようの ひみつを みつけて にわを すすもう',
    story: 'にわには ふしぎな もようが いっぱい。\nパターンを みつけて、\nつぎに くる かたちを あてよう！',
    wall: '🌸',
    tint: 'rgba(180,80,180,.22)',
  },
  {
    id: 'zone-bigsub',
    name: 'ふたけたの ひきざん',
    emoji: '🏚️',
    bgFrom: 'from-stone-100',
    bgTo: 'to-orange-200',
    unitIds: ['big-subtraction'],
    layerCount: 8,
    tagline: 'ふたけたから ひとけたを ひこう',
    story: 'ふたけたの まちの うらどおり。\nおおきい かずから ひとけたを ひくよ。\nくりさがりに きを つけて！',
    wall: '🧱',
    tint: 'rgba(150,110,70,.22)',
  },
  {
    id: 'zone-mul',
    name: 'かけざんの もり',
    emoji: '✖️',
    bgFrom: 'from-lime-100',
    bgTo: 'to-green-200',
    unitIds: ['multiplication'],
    layerCount: 8,
    tagline: 'かたまりで まとめて かぞえよう',
    story: 'おなじ かずの かたまりが\nいくつも ならぶ もり。\nかけざんで まとめて かぞえよう！',
    wall: '🌳',
    tint: 'rgba(80,160,90,.22)',
  },
  {
    id: 'zone-div',
    name: 'わけわけ どうくつ',
    emoji: '➗',
    bgFrom: 'from-slate-100',
    bgTo: 'to-gray-300',
    unitIds: ['division'],
    layerCount: 8,
    tagline: 'おなじ かずずつ わけよう',
    story: 'くらい どうくつで みつけた おかし。\nみんなで おなじ かずずつ\nわけて みよう！',
    wall: '🪨',
    tint: 'rgba(110,110,120,.22)',
  },
  {
    id: 'zone-divrem',
    name: 'あまりんぼの たに',
    emoji: '🧩',
    bgFrom: 'from-pink-100',
    bgTo: 'to-rose-200',
    unitIds: ['division-remainder'],
    layerCount: 8,
    tagline: 'わりきれない かずに ちょうせん',
    story: 'わけても わけても のこっちゃう。\nこれが「あまり」だよ。\nなんこ あまるか かんがえよう！',
    wall: '🍰',
    tint: 'rgba(200,90,130,.22)',
  },
  {
    id: 'zone-mix',
    name: 'ちからだめし ひろば',
    emoji: '🌈',
    bgFrom: 'from-amber-100',
    bgTo: 'to-pink-200',
    unitIds: ['cherry-calc', 'big-addition', 'big-subtraction', 'multiplication', 'division'],
    layerCount: 8,
    tagline: 'いままでの ちからで ぜんぶ とこう',
    story: 'いままで おぼえた ぜんぶの ちから。\nたしざんも かけざんも わりざんも、\nここで ためして みよう！',
    wall: '⭐',
    tint: 'rgba(200,140,80,.22)',
  },
  {
    id: 'zone-boss',
    name: 'だいとしょかんの おく',
    emoji: '🌟',
    bgFrom: 'from-amber-100',
    bgTo: 'to-yellow-200',
    unitIds: ['make-ten', 'addition', 'subtraction', 'cherry-calc', 'big-addition'],
    layerCount: 10,
    tagline: 'ぜんぶの ちしきで ラスボスに ちょうせん！',
    story: 'いよいよ としょかんの おくへ。\nこれまで おぼえた ぜんぶを つかって、\nさいごの ひみつを といてみよう！',
    wall: '📚',
    tint: 'rgba(200,150,50,.22)',
  },
];

export function getZone(id: string): AdventureZoneDef {
  const z = MATH_ADVENTURE_ZONES.find((z) => z.id === id);
  if (!z) throw new Error(`zone not found: ${id}`);
  return z;
}
