import type { WorldDef } from './types';

// もじギア・ファクトリーの世界（§7・§13）。
// 1〜10 は教材（lineIds が1つ）、11〜13 は腕試し（lineIds が複数）。
// アンロックは配列順の直線。新しい世界は「末尾に追加」する（途中挿入しない）。

export const WORLDS: WorldDef[] = [
  {
    id: 'zoo',
    name: 'どうぶつえん',
    emoji: '🦁',
    friend: 'くまの えんちょう',
    story: 'たいへん！ オリが あかないの。\nどうぶつの ことばで たすけてね！',
    tint: 'from-emerald-100 to-lime-100',
    lineIds: ['count-mora'],
  },
  {
    id: 'sweets',
    name: 'おかしのくに',
    emoji: '🍰',
    friend: 'おかしの コック',
    story: 'おかしを やきたいの。\nさいしょの おとで オーブンを つけて！',
    tint: 'from-pink-100 to-orange-100',
    lineIds: ['first-mora'],
  },
  {
    id: 'space',
    name: 'うちゅう',
    emoji: '🚀',
    friend: 'うちゅうじん',
    story: 'ロケットの ねんりょうは ことば！\nおしりの おとを つなげて はっしゃ！',
    tint: 'from-indigo-200 to-slate-200',
    lineIds: ['last-mora'],
  },
  {
    id: 'sea',
    name: 'うみ',
    emoji: '🌊',
    friend: 'たこ',
    story: 'おなじ おとの さかなを\nあつめて おくれ〜！',
    tint: 'from-sky-100 to-cyan-100',
    lineIds: ['match-sound'],
  },
  {
    id: 'ghost',
    name: 'おばけやしき',
    emoji: '👻',
    friend: 'こわかわ おばけ',
    story: 'もじを ならべて\nおばけの なまえを よんでね〜',
    tint: 'from-purple-200 to-fuchsia-100',
    lineIds: ['build-word'],
  },
  {
    id: 'vehicle',
    name: 'のりもの きち',
    emoji: '🚒',
    friend: 'しょうぼうし',
    story: 'ルールカードを みて\nしゅつどう する ギアを えらんで！',
    tint: 'from-red-100 to-amber-100',
    lineIds: ['rule-card'],
  },
  {
    id: 'garden',
    name: 'ひみつの にわ',
    emoji: '🌸',
    friend: 'ようせい',
    story: 'おとを ひとつ ぬくと\nべつの はなが さくよ',
    tint: 'from-lime-100 to-rose-100',
    lineIds: ['delete-mora'],
  },
  {
    id: 'dino',
    name: 'きょうりゅうの しま',
    emoji: '🦕',
    friend: 'あかちゃん きょうりゅう',
    story: 'NOTくんが きた！\nことばが さかさまに なっちゃう！',
    tint: 'from-green-200 to-teal-100',
    lineIds: ['reverse-word'],
  },
  {
    id: 'circus',
    name: 'サーカス',
    emoji: '🎪',
    friend: 'ピエロ',
    story: 'キラキラの とくべつ ギア！\nだくてんや ちいさい じに ちゅうい',
    tint: 'from-rose-200 to-yellow-100',
    lineIds: ['special-mora'],
  },
  {
    id: 'factory',
    name: 'IF-くん だいこうじょう',
    emoji: '🤖',
    friend: 'みんな',
    story: 'さいごの だいこうじょう！\nぜんぶの ちからで うごかそう！',
    tint: 'from-amber-200 to-yellow-200',
    lineIds: ['if-factory'],
  },
  // ── 11〜13: ボスのあとに ひらく 上級の せかい（腕試し・組み合わせ）──
  {
    id: 'island',
    name: 'なぞなぞ アイランド',
    emoji: '🏝️',
    friend: 'なぞなぞマスター',
    story: 'たからの なぞなぞ！\nいろんな もんだいを といてね',
    tint: 'from-yellow-100 to-sky-100',
    lineIds: ['count-mora', 'first-mora', 'last-mora', 'match-sound'],
  },
  {
    id: 'amusement',
    name: 'ことばの ゆうえんち',
    emoji: '🎡',
    friend: 'あんない係ロボ',
    story: 'アトラクションごとに\nちがう ギアの おしごと！',
    tint: 'from-fuchsia-100 to-cyan-100',
    lineIds: ['match-sound', 'build-word', 'delete-mora'],
  },
  {
    id: 'tower',
    name: 'さかさま タワー',
    emoji: '🌌',
    friend: 'なかよし NOTくん',
    story: 'のぼるほど さかさま！\nいちばん むずかしい たびだよ',
    tint: 'from-violet-300 to-indigo-200',
    lineIds: ['reverse-word', 'special-mora', 'rule-card'],
    startLevel: 2,
    difficulty: { special: true },
  },
  // ── 14〜: さらに上級（新メカ＋混合・難易度すこし上げ）──
  {
    id: 'echo-valley',
    name: 'こだまの たに',
    emoji: '🏔️',
    friend: 'やまびこ',
    story: 'まんなかの おとを\nこだまさせて すすもう！',
    tint: 'from-cyan-200 to-emerald-100',
    lineIds: ['middle-mora'],
    startLevel: 2,
  },
  {
    id: 'music-hall',
    name: 'おとあわせ ホール',
    emoji: '🎵',
    friend: 'おんがくか ロボ',
    story: 'おしりの おとが おなじ\nなかまで えんそうだ！',
    tint: 'from-rose-200 to-amber-100',
    lineIds: ['rhyme-match'],
    startLevel: 2,
  },
  {
    id: 'yatai',
    name: 'やたいの よこちょう',
    emoji: '🍜',
    friend: 'やたいの おやじ',
    story: 'おみせごとに ちがう おしごと！\nいろんな おとで ちゅうもん',
    tint: 'from-orange-200 to-red-100',
    lineIds: ['first-mora', 'last-mora', 'middle-mora', 'rhyme-match'],
    startLevel: 2,
  },
  {
    id: 'dragon',
    name: 'ドラゴンの すみか',
    emoji: '🐉',
    friend: 'ドラゴン',
    story: 'もじを あやつる まほう！\nならべて・ぬいて・さかさまに',
    tint: 'from-red-300 to-purple-200',
    lineIds: ['build-word', 'delete-mora', 'reverse-word'],
    startLevel: 3,
  },
  {
    id: 'castle',
    name: 'ことばの しろ',
    emoji: '👑',
    friend: 'ことばの おう',
    story: 'さいごの しろ！\nぜんぶの ちからを みせて！',
    tint: 'from-yellow-300 to-amber-200',
    lineIds: ['first-mora', 'last-mora', 'middle-mora', 'rhyme-match', 'build-word', 'delete-mora', 'reverse-word', 'rule-card'],
    startLevel: 3,
    difficulty: { special: true },
  },
  // ── 19〜: 「ながい ことば」と「○ばんめ」の バリエーション（文字数おおめ・位置の抽出）──
  {
    id: 'number-town',
    name: 'ナンバー こうじょう',
    emoji: '🔢',
    friend: 'カウンター ロボ',
    story: 'なんばんめの おとかな？\nばんごうを みて さがそう！',
    tint: 'from-sky-200 to-indigo-100',
    lineIds: ['nth-mora'],
    startLevel: 2,
    difficulty: { minMora: 3, maxMora: 4 },
  },
  {
    id: 'long-train',
    name: 'ながーい れっしゃ',
    emoji: '🚃',
    friend: 'しゃしょう さん',
    story: 'ながーい ことばだよ！\nいくつの おとか かぞえてね',
    tint: 'from-teal-200 to-emerald-100',
    lineIds: ['count-mora'],
    startLevel: 3,
    difficulty: { minMora: 5, maxMora: 6 },
  },
  {
    id: 'whale-bay',
    name: 'おおきな くじら',
    emoji: '🐋',
    friend: 'くじら',
    story: 'ながい ことばの\nさいしょと おしりの おと！',
    tint: 'from-blue-200 to-cyan-100',
    lineIds: ['first-mora', 'last-mora'],
    startLevel: 3,
    difficulty: { minMora: 5, maxMora: 6 },
  },
  {
    id: 'merry-build',
    name: 'メリーゴーランド',
    emoji: '🎠',
    friend: 'もくば',
    story: 'ながい ことばを\nじゅんばんに つくろう！',
    tint: 'from-pink-200 to-rose-100',
    lineIds: ['build-word'],
    startLevel: 3,
    difficulty: { minMora: 4, maxMora: 5 },
  },
  {
    id: 'detective',
    name: 'ことば たんてい',
    emoji: '🕵️',
    friend: 'たんてい',
    story: 'おとの ばしょを さがす\nめいたんてい だ！',
    tint: 'from-stone-300 to-amber-100',
    lineIds: ['first-mora', 'last-mora', 'middle-mora', 'nth-mora', 'count-mora'],
    startLevel: 3,
    difficulty: { minMora: 3, maxMora: 5 },
  },
  {
    id: 'word-king',
    name: 'ことばの だいまおう',
    emoji: '🐲',
    friend: 'だいまおう',
    story: 'さいごの ちょうせん！\nながい ことば ぜんぶの ちから！',
    tint: 'from-purple-300 to-red-200',
    lineIds: ['nth-mora', 'first-mora', 'last-mora', 'middle-mora', 'build-word', 'count-mora', 'special-mora'],
    startLevel: 4,
    difficulty: { minMora: 4, maxMora: 5 },
  },
  // ── 25〜32: 音韻「操作」系の 上級ゾーン（置換・添加・転置…＝PA階層の最上位）──
  {
    id: 'donut-factory',
    name: 'ドーナツ こうじょう',
    emoji: '🍩',
    friend: 'パティシエ ロボ',
    story: 'まんなかの あなを あけよう！\nまんなかの おとを ぬいてね',
    tint: 'from-amber-200 to-pink-100',
    lineIds: ['delete-medial'],
    startLevel: 2,
  },
  {
    id: 'plus-tower',
    name: 'ぷらす タワー',
    emoji: '➕',
    friend: 'つみあげ ロボ',
    story: 'おとを たすと ことばが のびる！\nなにを たすか かんがえて',
    tint: 'from-lime-200 to-emerald-100',
    lineIds: ['add-mora'],
    startLevel: 2,
  },
  {
    id: 'henshin-lab',
    name: 'へんしん けんきゅうじょ',
    emoji: '🪄',
    friend: 'へんしん マスター',
    story: 'おとを ひとつ かえると…\nべつの ことばに へんしん！',
    tint: 'from-violet-200 to-fuchsia-100',
    lineIds: ['substitute-mora'],
    startLevel: 2,
  },
  {
    id: 'cave-detective',
    name: 'たんけん どうくつ',
    emoji: '🔦',
    friend: 'たんけんか',
    story: 'この おとは なんばんめ？\nライトで てらして さがそう！',
    tint: 'from-stone-300 to-sky-100',
    lineIds: ['find-position'],
    startLevel: 2,
    difficulty: { minMora: 3, maxMora: 4 },
  },
  {
    id: 'amanojaku',
    name: 'あまのじゃく こうぼう',
    emoji: '🌀',
    friend: 'あまのじゃく NOTくん',
    story: 'さいしょと おしりを\nいれかえちゃう こうぼう！',
    tint: 'from-teal-200 to-indigo-100',
    lineIds: ['swap-mora'],
    startLevel: 2,
    difficulty: { minMora: 3, maxMora: 4 },
  },
  {
    id: 'sakasama-tunnel',
    name: 'さかさま トンネル',
    emoji: '🐍',
    friend: 'ながい へび',
    story: 'ながい ことばを\nぜんぶ さかさまに！',
    tint: 'from-green-300 to-lime-200',
    lineIds: ['reverse-word'],
    startLevel: 3,
    difficulty: { minMora: 4, maxMora: 5 },
  },
  {
    id: 'kirakira-mine',
    name: 'キラキラ さいくつじょう',
    emoji: '✨',
    friend: 'たからほり ロボ',
    story: 'とくべつな おとを\nぬいたり かえたり さかさまに！',
    tint: 'from-yellow-200 to-rose-200',
    lineIds: ['delete-medial', 'reverse-word', 'substitute-mora'],
    startLevel: 3,
    difficulty: { special: true },
  },
  {
    id: 'daimahou',
    name: 'ことばの だいまほうつかい',
    emoji: '🐲',
    friend: 'だいまほうつかい',
    story: 'さいごの ちょうせん！\nおきかえ・いれかえ ぜんぶの まほう！',
    tint: 'from-purple-400 to-rose-300',
    lineIds: ['substitute-mora', 'swap-mora', 'delete-medial', 'find-position', 'reverse-word'],
    startLevel: 4,
    difficulty: { minMora: 4, maxMora: 5 },
  },
  // ── 33〜40「でんせつ」: たつじんの うえ。濁点/半濁点の操作・なかまはずれ・長語混合の 最上級 ──
  {
    id: 'tenten-factory',
    name: 'てんてん こうじょう',
    emoji: '🔉',
    friend: 'てんてん ロボ',
    story: 'てんてんを つけると\nおとが かわるよ！',
    tint: 'from-sky-300 to-blue-200',
    lineIds: ['voice-mora'],
    startLevel: 3,
  },
  {
    id: 'maru-atelier',
    name: 'まる アトリエ',
    emoji: '🅿️',
    friend: 'まる ロボ',
    story: 'まる(はんだくてん)で\nぱぴぷぺぽ に へんしん！',
    tint: 'from-pink-300 to-rose-200',
    lineIds: ['semivoice-mora'],
    startLevel: 3,
  },
  {
    id: 'nakama-hazure',
    name: 'なかまはずれ ランド',
    emoji: '🎯',
    friend: 'みみの いい うさぎ',
    story: 'ひとつだけ おとが ちがう！\nなかまはずれを みつけて',
    tint: 'from-amber-300 to-yellow-200',
    lineIds: ['odd-one-out'],
    startLevel: 3,
  },
  {
    id: 'double-amanojaku',
    name: 'ダブル あまのじゃく',
    emoji: '🌀',
    friend: 'おおきな NOTくん',
    story: 'ながい ことばも\nさかさま・いれかえ！',
    tint: 'from-teal-300 to-cyan-200',
    lineIds: ['swap-mora', 'reverse-word'],
    startLevel: 4,
    difficulty: { minMora: 4, maxMora: 5 },
  },
  {
    id: 'mienai-tantei',
    name: 'みえない たんてい',
    emoji: '🔦',
    friend: 'めいたんてい',
    story: 'ながい ことばの\nおとの ばしょを さがせ！',
    tint: 'from-slate-400 to-indigo-200',
    lineIds: ['find-position', 'nth-mora'],
    startLevel: 4,
    difficulty: { minMora: 5, maxMora: 6 },
  },
  {
    id: 'dakuten-mine',
    name: 'だくてん さいくつじょう',
    emoji: '✨',
    friend: 'たからほり マスター',
    story: 'てんてん・まる・おきかえ\nとくべつな おとの おおあばれ！',
    tint: 'from-fuchsia-300 to-amber-200',
    lineIds: ['voice-mora', 'semivoice-mora', 'substitute-mora'],
    startLevel: 4,
    difficulty: { special: true },
  },
  {
    id: 'sousa-taikai',
    name: 'そうさ たいかい',
    emoji: '🐉',
    friend: 'チャンピオン ドラゴン',
    story: 'おきかえ・いれかえ・ぬく・さかさま\nぜんぶ ながい ことばで！',
    tint: 'from-red-400 to-purple-300',
    lineIds: ['substitute-mora', 'swap-mora', 'delete-medial', 'reverse-word'],
    startLevel: 4,
    difficulty: { minMora: 4, maxMora: 5 },
  },
  {
    id: 'densetsu-boss',
    name: 'でんせつの ことばおう',
    emoji: '🏆',
    friend: 'でんせつ おう',
    story: 'でんせつの ちょうせん！\nぜんぶの ちからを みせて！',
    tint: 'from-yellow-400 to-red-300',
    lineIds: ['voice-mora', 'odd-one-out', 'substitute-mora', 'swap-mora', 'find-position', 'reverse-word'],
    startLevel: 4,
    difficulty: { minMora: 4, maxMora: 5 },
  },
  // ── 41〜48「おうごん」: でんせつの さらに上。新メカ3種(数える/しりとり/ばらばら)＋難混合 ──
  {
    id: 'count-mountain',
    name: 'かぞえる さんちょう',
    emoji: '🔢',
    friend: 'カウント せんにん',
    story: 'おなじ おとは いくつ？\nよーく きいて かぞえてね！',
    tint: 'from-sky-300 to-cyan-200',
    lineIds: ['count-target-mora'],
    startLevel: 3,
    difficulty: { minMora: 3, maxMora: 5 },
  },
  {
    id: 'shiritori-train',
    name: 'しりとり れっしゃ',
    emoji: '🚂',
    friend: 'しゃしょう マスター',
    story: 'しりとりで れっしゃを つなごう！\nおしりの おと→つぎの あたま',
    tint: 'from-emerald-300 to-teal-200',
    lineIds: ['shiritori-chain'],
    startLevel: 3,
  },
  {
    id: 'anagram-workshop',
    name: 'ばらばら こうぼう',
    emoji: '🧩',
    friend: 'パズル ロボ',
    story: 'もじが ばらばら！\nならべて ことばに もどして',
    tint: 'from-violet-300 to-purple-200',
    lineIds: ['anagram'],
    startLevel: 3,
    difficulty: { minMora: 3, maxMora: 4 },
  },
  {
    id: 'volcano-trial',
    name: 'かざんの しれん',
    emoji: '🌋',
    friend: 'ほのお ドラゴン',
    story: 'ながい ことばを\nいれかえ・さかさま！',
    tint: 'from-red-400 to-orange-300',
    lineIds: ['swap-mora', 'reverse-word'],
    startLevel: 4,
    difficulty: { minMora: 4, maxMora: 5 },
  },
  {
    id: 'henshin-casino',
    name: 'へんしん カジノ',
    emoji: '🎰',
    friend: 'マジシャン',
    story: 'おきかえ・てんてん・まる！\nへんしんの まほうだ',
    tint: 'from-fuchsia-300 to-rose-300',
    lineIds: ['substitute-mora', 'voice-mora', 'semivoice-mora'],
    startLevel: 4,
    difficulty: { special: true },
  },
  {
    id: 'ufo-mystery',
    name: 'なぞの えんばん',
    emoji: '🛸',
    friend: 'うちゅうの おう',
    story: 'ながい ことばの\nおとの ばしょと かず！',
    tint: 'from-indigo-400 to-slate-300',
    lineIds: ['find-position', 'nth-mora', 'count-target-mora'],
    startLevel: 4,
    difficulty: { minMora: 5, maxMora: 6 },
  },
  {
    id: 'word-keep',
    name: 'ことばの てんしゅ',
    emoji: '🏯',
    friend: 'しろの ぬし',
    story: 'ならべて・しりとり・ぬく！\nことばの しろを まもれ',
    tint: 'from-amber-300 to-yellow-300',
    lineIds: ['anagram', 'shiritori-chain', 'delete-medial'],
    startLevel: 4,
    difficulty: { minMora: 3, maxMora: 4 },
  },
  {
    id: 'master-champion',
    name: 'マスター チャンピオン',
    emoji: '☄️',
    friend: 'みんな',
    story: 'さいごの ちょうせん！\nおうごんの ちからを みせて！',
    tint: 'from-yellow-400 to-amber-300',
    lineIds: ['count-target-mora', 'shiritori-chain', 'anagram', 'swap-mora', 'substitute-mora', 'reverse-word', 'find-position'],
    startLevel: 4,
    difficulty: { minMora: 4, maxMora: 5 },
  },
  // ── 49〜58「エビデンス・バラエティ」: PA(音韻認識)階層の スキルごとに テーマを わけた 10ゾーン。
  //    新メカ「音の合成(blend)」＋既存メカの 別組み合わせで、ねらう力を 1ゾーン1つに しぼる。──
  {
    id: 'seed-field',
    name: 'ことばの たねばたけ',
    emoji: '🌱',
    friend: 'にわの ようせい',
    story: 'ばらばらの おとを つなげると…\nたねから ことばが さくよ！',
    tint: 'from-green-200 to-yellow-100',
    lineIds: ['blend-mora'], // 聴覚ブレンディング（合成）＝読字力の 二大予測スキルの ひとつ
    startLevel: 2,
  },
  {
    id: 'oto-station',
    name: 'おとつなぎ えき',
    emoji: '🚉',
    friend: 'しゃしょう ロボ',
    story: 'おしりの おとで つぎへ つなぐ！\nしりとりの えきだよ',
    tint: 'from-sky-200 to-teal-100',
    lineIds: ['last-mora', 'first-mora', 'shiritori-chain'], // 語尾→語頭の連鎖＝モーラ意識（しりとり）
    startLevel: 2,
  },
  {
    id: 'oto-aquarium',
    name: 'おとあて すいぞくかん',
    emoji: '🐠',
    friend: 'いるか',
    story: 'おなじ おとの さかなを さがそう！\nさいしょ や おしりを よく きいて',
    tint: 'from-cyan-200 to-blue-100',
    lineIds: ['match-sound', 'rhyme-match'], // 頭韻＆押韻の感受性（Bradley & Bryant の古典課題）
    startLevel: 2,
  },
  {
    id: 'nakama-forest',
    name: 'なかまはずれ もり',
    emoji: '🦉',
    friend: 'みみの いい ふくろう',
    story: 'ひとつだけ おとが ちがう！\nなかまはずれを みみで みつけて',
    tint: 'from-amber-200 to-lime-100',
    lineIds: ['odd-one-out', 'match-sound'], // 音オドリティ＝同定より上位（比べて 抑制する）
    startLevel: 3,
  },
  {
    id: 'kazoe-mountain',
    name: 'かぞえる ことばやま',
    emoji: '🏔️',
    friend: 'やぎ せんせい',
    story: 'おとは いくつ かな？\nおなじ おとも かぞえてみよう',
    tint: 'from-stone-200 to-sky-100',
    lineIds: ['count-mora', 'count-target-mora'], // 音韻分析＋計数（分節化）
    startLevel: 3,
    difficulty: { minMora: 3, maxMora: 5 },
  },
  {
    id: 'banme-detective',
    name: 'ばんめ たんていしゃ',
    emoji: '🔎',
    friend: 'おとの たんてい',
    story: 'なんばんめの おと？\nまんなかも さがせる たんていだ',
    tint: 'from-slate-300 to-indigo-100',
    lineIds: ['nth-mora', 'find-position', 'middle-mora'], // 位置の抽出・同定（語中＝発達的に最難）
    startLevel: 3,
    difficulty: { minMora: 3, maxMora: 5 },
  },
  {
    id: 'nukitori-factory',
    name: 'ぬきとり ファクトリー',
    emoji: '🏭',
    friend: 'ぬきとり ロボ',
    story: 'おとを ぬいたり たしたり！\nことばが かわる こうじょう',
    tint: 'from-zinc-300 to-amber-100',
    lineIds: ['delete-mora', 'delete-medial', 'add-mora'], // 削除（語頭/語中）と添加＝対の操作系
    startLevel: 3,
  },
  {
    id: 'henshin-onsen',
    name: 'へんしん おんせん',
    emoji: '♨️',
    friend: 'ばけだぬき',
    story: 'おとを かえたり てんてんを つけたり！\nへんしんの おゆだよ',
    tint: 'from-rose-200 to-fuchsia-100',
    lineIds: ['substitute-mora', 'add-mora', 'voice-mora'], // 置換・添加・濁点＝音韻操作の上位
    startLevel: 3,
  },
  {
    id: 'sakasama-cave',
    name: 'さかさま どうくつ',
    emoji: '🦇',
    friend: 'さかさ こうもり',
    story: 'おとを さかさまに！\nさいしょと おしりも いれかえる',
    tint: 'from-violet-300 to-slate-200',
    lineIds: ['reverse-word', 'swap-mora'], // 逆唱・転置＝ワーキングメモリ最大級
    startLevel: 4,
    difficulty: { minMora: 3, maxMora: 4 },
  },
  {
    id: 'word-lab',
    name: 'ことばの だいけんきゅうじょ',
    emoji: '🧪',
    friend: 'ことば はかせ',
    story: 'さいごの けんきゅう！\nつなぐ・さがす・かえる ぜんぶの ちから！',
    tint: 'from-purple-300 to-red-200',
    lineIds: ['blend-mora', 'nth-mora', 'substitute-mora', 'swap-mora', 'count-target-mora', 'find-position'], // 合成＋抽出＋操作の総合ボス
    startLevel: 4,
    difficulty: { minMora: 4, maxMora: 5 },
  },
];

export function getWorld(id: string): WorldDef | undefined {
  return WORLDS.find((w) => w.id === id);
}
